name: Shop
favicon: null
layout_spectrum: 0.4792189975269139
typography_spectrum: 0.3014145321212709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4975314463954419
  lightness: 0.5141397486440837
  saturation: 0.8942652761470526
  rhythmicContrast: 0.5877963362727314
purpose: []
